# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
	pod 'PayFortSDK'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManagerSwift'
  
  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
